
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tumax
 */
public class Editor extends javax.swing.JFrame {
    
    private java.awt.Font fuentePr;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editor.class.getName());

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Editor");
        this.setSize(500, 300);
        this.setResizable(false);
        
        jtxtaEditor.requestFocus();
        fuentePr = jtxtaEditor.getFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtCortar = new javax.swing.JButton();
        jbtCopiar = new javax.swing.JButton();
        jbtPegar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuArchivo = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jmnuEditar = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmnuOpciones = new javax.swing.JMenu();
        jmnuFuente = new javax.swing.JMenu();
        jmItemCourierNew = new javax.swing.JMenuItem();
        jmItemArial = new javax.swing.JMenuItem();
        jmItemFPredeterminada = new javax.swing.JMenuItem();
        jmnuTam = new javax.swing.JMenu();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jmItemTPredeterminado = new javax.swing.JMenuItem();
        jmnuColor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmnuEstilo = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbtCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tijeras.png"))); // NOI18N
        jbtCortar.setToolTipText("Cortar");
        jbtCortar.setFocusPainted(false);
        jbtCortar.setFocusable(false);
        jbtCortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCortar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtCortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCortar.addActionListener(this::jbtCortarActionPerformed);
        jToolBar1.add(jbtCortar);

        jbtCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/copiar.png"))); // NOI18N
        jbtCopiar.setToolTipText("Copiar");
        jbtCopiar.setFocusPainted(false);
        jbtCopiar.setFocusable(false);
        jbtCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCopiar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCopiar.addActionListener(this::jbtCopiarActionPerformed);
        jToolBar1.add(jbtCopiar);

        jbtPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pegar.png"))); // NOI18N
        jbtPegar.setToolTipText("Pegar");
        jbtPegar.setFocusPainted(false);
        jbtPegar.setFocusable(false);
        jbtPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPegar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPegar.addActionListener(this::jbtPegarActionPerformed);
        jToolBar1.add(jbtPegar);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jScrollPane1.setViewportView(jtxtaEditor);

        jmnuArchivo.setMnemonic('A');
        jmnuArchivo.setText("Archivo");

        jmItemSalir.setMnemonic('S');
        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(this::jmItemSalirActionPerformed);
        jmnuArchivo.add(jmItemSalir);

        jMenuBar1.add(jmnuArchivo);

        jmnuEditar.setMnemonic('E');
        jmnuEditar.setText("Editar");

        jmItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCortar.setMnemonic('T');
        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(this::jmItemCortarActionPerformed);
        jmnuEditar.add(jmItemCortar);

        jmItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCopiar.setMnemonic('C');
        jmItemCopiar.setText("Copiar");
        jmItemCopiar.addActionListener(this::jmItemCopiarActionPerformed);
        jmnuEditar.add(jmItemCopiar);

        jmItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemPegar.setMnemonic('P');
        jmItemPegar.setText("Pegar");
        jmItemPegar.addActionListener(this::jmItemPegarActionPerformed);
        jmnuEditar.add(jmItemPegar);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setMnemonic('B');
        jMenuItem9.setText("Borrar Todo");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jmnuEditar.add(jMenuItem9);

        jMenuBar1.add(jmnuEditar);

        jmnuOpciones.setMnemonic('O');
        jmnuOpciones.setText("Opciones");

        jmnuFuente.setMnemonic('F');
        jmnuFuente.setText("Fuente");

        jmItemCourierNew.setText("Courier New");
        jmItemCourierNew.addActionListener(this::jmItemCourierNewActionPerformed);
        jmnuFuente.add(jmItemCourierNew);

        jmItemArial.setText("Arial");
        jmItemArial.addActionListener(this::jmItemArialActionPerformed);
        jmnuFuente.add(jmItemArial);

        jmItemFPredeterminada.setText("Predeterminada");
        jmItemFPredeterminada.addActionListener(this::jmItemFPredeterminadaActionPerformed);
        jmnuFuente.add(jmItemFPredeterminada);

        jmnuOpciones.add(jmnuFuente);

        jmnuTam.setMnemonic('T');
        jmnuTam.setText("Tamaño");

        jmItem16.setText("16");
        jmItem16.addActionListener(this::jmItem16ActionPerformed);
        jmnuTam.add(jmItem16);

        jmItem24.setText("24");
        jmItem24.addActionListener(this::jmItem24ActionPerformed);
        jmnuTam.add(jmItem24);

        jmItemTPredeterminado.setText("Predeterminado");
        jmItemTPredeterminado.addActionListener(this::jmItemTPredeterminadoActionPerformed);
        jmnuTam.add(jmItemTPredeterminado);

        jmnuOpciones.add(jmnuTam);

        jmnuColor.setMnemonic('C');
        jmnuColor.setText("Colores");

        jMenuItem1.setText("Rojo");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jmnuColor.add(jMenuItem1);

        jMenuItem2.setText("Azul");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jmnuColor.add(jMenuItem2);

        jMenuItem3.setText("Amarillo");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jmnuColor.add(jMenuItem3);

        jMenuItem4.setText("Predeterminado");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jmnuColor.add(jMenuItem4);

        jmnuOpciones.add(jmnuColor);

        jmnuEstilo.setMnemonic('E');
        jmnuEstilo.setText("Estilos");

        jMenuItem5.setText("Negrita");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jmnuEstilo.add(jMenuItem5);

        jMenuItem6.setText("Cursiva");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jmnuEstilo.add(jMenuItem6);

        jMenuItem7.setText("Subrayado");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jmnuEstilo.add(jMenuItem7);

        jMenuItem8.setText("Sin Estilo");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jmnuEstilo.add(jMenuItem8);

        jmnuOpciones.add(jmnuEstilo);

        jMenuBar1.add(jmnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        jtxtaEditor.cut();
    }//GEN-LAST:event_jmItemCortarActionPerformed

    private void jbtCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCortarActionPerformed
        jtxtaEditor.cut();
    }//GEN-LAST:event_jbtCortarActionPerformed

    private void jmItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCopiarActionPerformed
        jtxtaEditor.copy();
    }//GEN-LAST:event_jmItemCopiarActionPerformed

    private void jbtCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCopiarActionPerformed
        jtxtaEditor.copy();
    }//GEN-LAST:event_jbtCopiarActionPerformed

    private void jmItemPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemPegarActionPerformed
        jtxtaEditor.paste();
    }//GEN-LAST:event_jmItemPegarActionPerformed

    private void jbtPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPegarActionPerformed
        jtxtaEditor.paste();
    }//GEN-LAST:event_jbtPegarActionPerformed

    private void jmItemCourierNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCourierNewActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font("Courier New", f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemCourierNewActionPerformed

    private void jmItemArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemArialActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font("Arial", f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemArialActionPerformed

    private void jmItemFPredeterminadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemFPredeterminadaActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(fuentePr.getFamily(), f.getStyle(), f.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemFPredeterminadaActionPerformed

    private void jmItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem16ActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(), f.getStyle(), 16);
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItem16ActionPerformed

    private void jmItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem24ActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(), f.getStyle(), 24);
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItem24ActionPerformed

    private void jmItemTPredeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemTPredeterminadoActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(), f.getStyle(), fuentePr.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jmItemTPredeterminadoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jtxtaEditor.setForeground(Color.red);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jtxtaEditor.setForeground(Color.blue);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jtxtaEditor.setForeground(Color.yellow);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jtxtaEditor.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        jtxtaEditor.setFont(f.deriveFont(java.awt.Font.BOLD));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        jtxtaEditor.setFont(f.deriveFont(java.awt.Font.ITALIC));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jtxtaEditor.setFont(jtxtaEditor.getFont().deriveFont(java.util.Collections.singletonMap(java.awt.font.TextAttribute.UNDERLINE, java.awt.font.TextAttribute.UNDERLINE_ON)));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        java.awt.Font f = jtxtaEditor.getFont();
        f = new java.awt.Font(f.getFamily(), fuentePr.getStyle(), fuentePr.getSize());
        jtxtaEditor.setFont(f);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jtxtaEditor.setText("");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtCopiar;
    private javax.swing.JButton jbtCortar;
    private javax.swing.JButton jbtPegar;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemArial;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCourierNew;
    private javax.swing.JMenuItem jmItemFPredeterminada;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemTPredeterminado;
    private javax.swing.JMenu jmnuArchivo;
    private javax.swing.JMenu jmnuColor;
    private javax.swing.JMenu jmnuEditar;
    private javax.swing.JMenu jmnuEstilo;
    private javax.swing.JMenu jmnuFuente;
    private javax.swing.JMenu jmnuOpciones;
    private javax.swing.JMenu jmnuTam;
    private javax.swing.JTextArea jtxtaEditor;
    // End of variables declaration//GEN-END:variables
}
